# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-15 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_activity', models.DateTimeField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fmb.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_maintenance', models.DateTimeField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fmb.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fmb.Equipment')),
            ],
        ),
        migrations.AddField(
            model_name='maintenanceactivity',
            name='maintenance_tast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fmb.MaintenanceTask'),
        ),
    ]
